-- Curated Kanto ecology for Crystal 251.
--
-- Every list is the exact ten-slot Generation I encounter table. Repetition
-- is deliberate: the ROM's cumulative buckets make the first entries common
-- and the final entry roughly 1.2%. A { species, level } entry overrides the
-- original slot's level; a bare species keeps the map's native progression.

local function habitat(day, night, combined, morning)
  return { day=day, night=night or day, combined=combined or day, morning=morning or day }
end

local E = {}

E.maps = {
  ROUTE_1={ tier=1, grass=habitat(
    {"PIDGEY","RATTATA","PIDGEY","RATTATA","SENTRET","PIDGEY","RATTATA","SENTRET","HOPPIP","SENTRET"},
    {"RATTATA","HOOTHOOT","RATTATA","HOOTHOOT","SENTRET","RATTATA","SPINARAK","HOOTHOOT","SENTRET","HOPPIP"},
    {"PIDGEY","RATTATA","HOOTHOOT","RATTATA","SENTRET","PIDGEY","SPINARAK","HOOTHOOT","HOPPIP","SENTRET"}) },
  ROUTE_2={ tier=1, grass=habitat(
    {"PIDGEY","RATTATA","WEEDLE","CATERPIE","PIDGEY","SENTRET","WEEDLE","CATERPIE","LEDYBA","SENTRET"},
    {"RATTATA","HOOTHOOT","SPINARAK","RATTATA","VENONAT","HOOTHOOT","SPINARAK","VENONAT","SENTRET","PICHU"},
    {"PIDGEY","RATTATA","WEEDLE","CATERPIE","HOOTHOOT","SENTRET","SPINARAK","VENONAT","LEDYBA","PICHU"}) },
  ROUTE_22={ tier=1, grass=habitat(
    {"RATTATA","NIDORAN_M","SPEAROW","NIDORAN_F","RATTATA","SPEAROW","NIDORAN_M","NIDORAN_F","PHANPY","SENTRET"},
    {"RATTATA","NIDORAN_F","HOOTHOOT","NIDORAN_M","RATTATA","HOOTHOOT","SPINARAK","PHANPY","SENTRET","SNUBBULL"},
    {"RATTATA","NIDORAN_M","SPEAROW","NIDORAN_F","HOOTHOOT","PHANPY","SENTRET","SPINARAK","SNUBBULL","SPEAROW"}) },
  VIRIDIAN_FOREST={ tier=1, grass=habitat(
    {"CATERPIE","WEEDLE","METAPOD","KAKUNA","CATERPIE","WEEDLE","PIKACHU","LEDYBA","PINECO",{"BULBASAUR",5}},
    {"SPINARAK","VENONAT","HOOTHOOT","SPINARAK","WEEDLE","CATERPIE","PIKACHU","VENONAT","PINECO",{"PICHU",4}},
    {"CATERPIE","WEEDLE","SPINARAK","METAPOD","KAKUNA","HOOTHOOT","PIKACHU","LEDYBA","PINECO",{"BULBASAUR",5}}) },
  ROUTE_3={ tier=2, grass=habitat(
    {"PIDGEY","SPEAROW","JIGGLYPUFF","PIDGEY","SPEAROW","JIGGLYPUFF","SNUBBULL","IGGLYBUFF","SENTRET","TOGEPI"},
    {"SPEAROW","HOOTHOOT","JIGGLYPUFF","RATTATA","HOOTHOOT","SNUBBULL","IGGLYBUFF","SPINARAK","SENTRET","TOGEPI"},
    {"PIDGEY","SPEAROW","JIGGLYPUFF","HOOTHOOT","SNUBBULL","IGGLYBUFF","RATTATA","SENTRET","SPINARAK","TOGEPI"}) },
  ROUTE_4={ tier=2, grass=habitat(
    {"RATTATA","SPEAROW","EKANS","SANDSHREW","RATTATA","SPEAROW","EKANS","SANDSHREW","PHANPY","HOPPIP"},
    {"RATTATA","SPEAROW","EKANS","SANDSHREW","HOOTHOOT","RATTATA","EKANS","PHANPY","SPINARAK","HOPPIP"},
    {"RATTATA","SPEAROW","EKANS","SANDSHREW","HOOTHOOT","PHANPY","RATTATA","SPINARAK","HOPPIP","SPEAROW"}) },
  ROUTE_24={ tier=2, grass=habitat(
    {"CATERPIE","WEEDLE","PIDGEY","ODDISH","CATERPIE","WEEDLE","PIDGEY","ABRA","ODDISH",{"CHIKORITA",10}},
    {"VENONAT","ODDISH","HOOTHOOT","BELLSPROUT","VENONAT","ODDISH","HOOTHOOT","ABRA","BELLSPROUT",{"CHIKORITA",10}},
    {"CATERPIE","WEEDLE","PIDGEY","ODDISH","BELLSPROUT","ABRA","HOOTHOOT","ODDISH","PIDGEY",{"CHIKORITA",10}}) },
  ROUTE_25={ tier=2, grass=habitat(
    {"CATERPIE","WEEDLE","PIDGEY","BELLSPROUT","CATERPIE","WEEDLE","PIDGEY","ABRA","BELLSPROUT","NATU"},
    {"VENONAT","ODDISH","HOOTHOOT","BELLSPROUT","VENONAT","ODDISH","HOOTHOOT","ABRA","BELLSPROUT","NATU"},
    {"CATERPIE","WEEDLE","PIDGEY","ODDISH","BELLSPROUT","ABRA","VENONAT","HOOTHOOT","BELLSPROUT","NATU"}) },
  MT_MOON_1F={ tier=2, grass=habitat({"ZUBAT","GEODUDE","ZUBAT","PARAS","GEODUDE","CLEFAIRY","ZUBAT","PARAS","CLEFFA","DUNSPARCE"}) },
  MT_MOON_B1F={ tier=2, grass=habitat({"ZUBAT","GEODUDE","PARAS","ZUBAT","GEODUDE","CLEFAIRY","PARAS","DUNSPARCE","CLEFFA","SHUCKLE"}) },
  MT_MOON_B2F={ tier=2, grass=habitat({"ZUBAT","GEODUDE","PARAS","CLEFAIRY","ZUBAT","GEODUDE","PARAS","DUNSPARCE","SHUCKLE","TOGEPI"}) },
  ROUTE_5={ tier=3, grass=habitat(
    {"ODDISH","PIDGEY","MEOWTH","BELLSPROUT","ODDISH","PIDGEY","MEOWTH","HOPPIP","SNUBBULL","SUNKERN"},
    {"ODDISH","MEOWTH","HOOTHOOT","BELLSPROUT","ODDISH","MEOWTH","HOOTHOOT","VENONAT","SNUBBULL","DROWZEE"},
    {"ODDISH","PIDGEY","MEOWTH","BELLSPROUT","HOPPIP","HOOTHOOT","SNUBBULL","VENONAT","ODDISH","SUNKERN"}) },
  ROUTE_6={ tier=3, grass=habitat(
    {"ODDISH","PIDGEY","MEOWTH","MANKEY","ODDISH","PIDGEY","MEOWTH","BELLSPROUT","YANMA","AIPOM"},
    {"ODDISH","MEOWTH","HOOTHOOT","MANKEY","ODDISH","MEOWTH","HOOTHOOT","VENONAT","YANMA","DROWZEE"},
    {"ODDISH","PIDGEY","MEOWTH","MANKEY","BELLSPROUT","HOOTHOOT","VENONAT","YANMA","ODDISH","AIPOM"}) },
  ROUTE_11={ tier=3, grass=habitat(
    {"EKANS","SPEAROW","DROWZEE","MEOWTH","SPEAROW","EKANS","DROWZEE","GIRAFARIG","STANTLER","FARFETCHD"},
    {"EKANS","RATTATA","DROWZEE","MEOWTH","HOOTHOOT","EKANS","DROWZEE","GIRAFARIG","MURKROW","STANTLER"},
    {"EKANS","SPEAROW","DROWZEE","MEOWTH","HOOTHOOT","RATTATA","GIRAFARIG","STANTLER","MURKROW","FARFETCHD"}) },
  DIGLETTS_CAVE={ tier=3, grass=habitat({"DIGLETT","DIGLETT","SANDSHREW","DIGLETT","PHANPY","SANDSHREW","DUGTRIO","DUNSPARCE","PHANPY","GLIGAR"}) },
  ROUTE_9={ tier=4, grass=habitat(
    {"SPEAROW","EKANS","SANDSHREW","SPEAROW","PHANPY","EKANS","SANDSHREW","MAREEP","GLIGAR","SKARMORY"},
    {"SPEAROW","EKANS","SANDSHREW","HOOTHOOT","SPEAROW","EKANS","SANDSHREW","MAREEP","GLIGAR","SKARMORY"},
    {"SPEAROW","EKANS","SANDSHREW","PHANPY","HOOTHOOT","MAREEP","SPEAROW","EKANS","GLIGAR","SKARMORY"}) },
  ROUTE_10={ tier=4, grass=habitat(
    {"VOLTORB","SPEAROW","EKANS","MAREEP","VOLTORB","SPEAROW","FLAAFFY","MAGNEMITE","GLIGAR","ELEKID"},
    {"VOLTORB","SPEAROW","EKANS","MAREEP","HOOTHOOT","VOLTORB","MAGNEMITE","MURKROW","GLIGAR","ELEKID"},
    {"VOLTORB","SPEAROW","EKANS","MAREEP","MAGNEMITE","HOOTHOOT","FLAAFFY","MURKROW","GLIGAR","ELEKID"}) },
  ROCK_TUNNEL_1F={ tier=4, grass=habitat({"ZUBAT","GEODUDE","MACHOP","ONIX","ZUBAT","GEODUDE","MACHOP","DUNSPARCE","SUDOWOODO","SHUCKLE"}) },
  ROCK_TUNNEL_B1F={ tier=4, grass=habitat({"ZUBAT","GEODUDE","MACHOP","ONIX","GOLBAT","GEODUDE","MACHOP","DUNSPARCE","WOBBUFFET","SHUCKLE"}) },
  POKEMON_TOWER_3F={ tier=4, grass=habitat(
    {"GASTLY","CUBONE","GASTLY","CUBONE","GASTLY","CUBONE","HAUNTER","MISDREAVUS","UNOWN","CUBONE"},
    {"GASTLY","GASTLY","CUBONE","GASTLY","MISDREAVUS","CUBONE","HAUNTER","MISDREAVUS","MURKROW","UNOWN"},
    {"GASTLY","CUBONE","GASTLY","MISDREAVUS","CUBONE","GASTLY","HAUNTER","MISDREAVUS","MURKROW","UNOWN"}) },
  POKEMON_TOWER_4F={ tier=4, grass=habitat(
    {"GASTLY","CUBONE","GASTLY","CUBONE","GASTLY","HAUNTER","CUBONE","MISDREAVUS","UNOWN","HAUNTER"},
    {"GASTLY","GASTLY","CUBONE","MISDREAVUS","GASTLY","HAUNTER","MISDREAVUS","MURKROW","UNOWN","HAUNTER"},
    {"GASTLY","CUBONE","GASTLY","MISDREAVUS","HAUNTER","CUBONE","MISDREAVUS","MURKROW","UNOWN","HAUNTER"}) },
  POKEMON_TOWER_5F={ tier=4, grass=habitat(
    {"GASTLY","CUBONE","GASTLY","HAUNTER","CUBONE","GASTLY","MISDREAVUS","UNOWN","HAUNTER","CUBONE"},
    {"GASTLY","HAUNTER","GASTLY","MISDREAVUS","CUBONE","HAUNTER","MISDREAVUS","MURKROW","UNOWN","HAUNTER"},
    {"GASTLY","CUBONE","HAUNTER","GASTLY","MISDREAVUS","CUBONE","HAUNTER","MURKROW","UNOWN","MISDREAVUS"}) },
  POKEMON_TOWER_6F={ tier=4, grass=habitat(
    {"GASTLY","CUBONE","HAUNTER","GASTLY","CUBONE","HAUNTER","MISDREAVUS","UNOWN","HAUNTER","MAROWAK"},
    {"GASTLY","HAUNTER","MISDREAVUS","GASTLY","CUBONE","HAUNTER","MISDREAVUS","MURKROW","UNOWN","MAROWAK"},
    {"GASTLY","CUBONE","HAUNTER","MISDREAVUS","GASTLY","HAUNTER","MURKROW","UNOWN","MAROWAK","MISDREAVUS"}) },
  POKEMON_TOWER_7F={ tier=4, grass=habitat(
    {"GASTLY","CUBONE","HAUNTER","GASTLY","HAUNTER","MISDREAVUS","CUBONE","UNOWN","MAROWAK","UNOWN"},
    {"GASTLY","HAUNTER","MISDREAVUS","GASTLY","HAUNTER","MURKROW","MISDREAVUS","UNOWN","MAROWAK","MURKROW"},
    {"GASTLY","CUBONE","HAUNTER","MISDREAVUS","GASTLY","MURKROW","UNOWN","MAROWAK","MISDREAVUS","UNOWN"}) },
  ROUTE_7={ tier=5, grass=habitat(
    {"PIDGEY","ODDISH","MEOWTH","GROWLITHE","PIDGEY","ODDISH","MEOWTH","SNUBBULL","AIPOM","EEVEE"},
    {"MEOWTH","ODDISH","HOOTHOOT","HOUNDOUR","MEOWTH","ODDISH","HOOTHOOT","MURKROW","AIPOM","YANMA"},
    {"PIDGEY","ODDISH","MEOWTH","GROWLITHE","HOOTHOOT","HOUNDOUR","SNUBBULL","MURKROW","AIPOM","EEVEE"}) },
  ROUTE_8={ tier=5, grass=habitat(
    {"PIDGEY","MANKEY","EKANS","GROWLITHE","PIDGEY","MANKEY","EKANS","SNUBBULL","STANTLER","YANMA"},
    {"MEOWTH","MANKEY","EKANS","HOUNDOUR","MEOWTH","MANKEY","EKANS","MURKROW","STANTLER","YANMA"},
    {"PIDGEY","MANKEY","EKANS","GROWLITHE","MEOWTH","HOUNDOUR","SNUBBULL","MURKROW","STANTLER","YANMA"}) },
  ROUTE_12={ tier=5, grass=habitat(
    {"ODDISH","PIDGEY","VENONAT","BELLSPROUT","ODDISH","PIDGEY","VENONAT","TANGELA","YANMA","FARFETCHD"},
    {"ODDISH","HOOTHOOT","VENONAT","BELLSPROUT","ODDISH","HOOTHOOT","VENONAT","TANGELA","MURKROW","WOBBUFFET"},
    {"ODDISH","PIDGEY","VENONAT","BELLSPROUT","HOOTHOOT","TANGELA","YANMA","ODDISH","VENONAT","WOBBUFFET"}) },
  ROUTE_13={ tier=5, grass=habitat(
    {"ODDISH","PIDGEY","VENONAT","DITTO","ODDISH","PIDGEY","VENONAT","TANGELA","YANMA","SMEARGLE"},
    {"ODDISH","HOOTHOOT","VENONAT","DITTO","ODDISH","HOOTHOOT","VENONAT","TANGELA","MURKROW","WOBBUFFET"},
    {"ODDISH","PIDGEY","VENONAT","DITTO","HOOTHOOT","TANGELA","YANMA","ODDISH","VENONAT","WOBBUFFET"}) },
  ROUTE_14={ tier=5, grass=habitat(
    {"ODDISH","PIDGEY","DITTO","VENONAT","ODDISH","PIDGEY","DITTO","GIRAFARIG","STANTLER","NATU"},
    {"ODDISH","HOOTHOOT","DITTO","VENONAT","ODDISH","HOOTHOOT","DITTO","GIRAFARIG","STANTLER","NATU"},
    {"ODDISH","PIDGEY","DITTO","VENONAT","HOOTHOOT","GIRAFARIG","STANTLER","NATU","ODDISH","DITTO"}) },
  ROUTE_15={ tier=5, grass=habitat(
    {"ODDISH","DITTO","PIDGEY","VENONAT","ODDISH","DITTO","PIDGEY","GIRAFARIG","STANTLER","SMEARGLE"},
    {"ODDISH","DITTO","HOOTHOOT","VENONAT","ODDISH","DITTO","HOOTHOOT","GIRAFARIG","STANTLER","WOBBUFFET"},
    {"ODDISH","DITTO","PIDGEY","VENONAT","HOOTHOOT","GIRAFARIG","STANTLER","SMEARGLE","ODDISH","DITTO"}) },
  POWER_PLANT={ tier=5, grass=habitat(
    {"VOLTORB","MAGNEMITE","VOLTORB","PIKACHU","MAREEP","MAGNEMITE","VOLTORB","ELEKID","MAGNETON","AMPHAROS"},
    {"VOLTORB","MAGNEMITE","VOLTORB","MAGNEMITE","MAREEP","ELECTABUZZ","VOLTORB","ELEKID","MAGNETON","ELECTRODE"},
    {"VOLTORB","MAGNEMITE","VOLTORB","PIKACHU","MAREEP","ELECTABUZZ","ELEKID","MAGNETON","VOLTORB","ELECTRODE"}) },
  ROUTE_16={ tier=6, grass=habitat(
    {"SPEAROW","RATICATE","DODUO","PONYTA","SPEAROW","RATICATE","DODUO","PONYTA","AIPOM","TEDDIURSA"},
    {"RATICATE","HOOTHOOT","DODUO","PONYTA","RATICATE","HOOTHOOT","DODUO","PONYTA","AIPOM","HOUNDOUR"},
    {"SPEAROW","RATICATE","DODUO","PONYTA","HOOTHOOT","AIPOM","TEDDIURSA","RATICATE","DODUO","HOUNDOUR"}) },
  ROUTE_17={ tier=6, grass=habitat(
    {"SPEAROW","RATICATE","DODUO","PONYTA","SPEAROW","RATICATE","DODUO","PONYTA","STANTLER","MILTANK"},
    {"RATICATE","HOOTHOOT","DODUO","PONYTA","RATICATE","HOOTHOOT","DODUO","PONYTA","STANTLER","MURKROW"},
    {"SPEAROW","RATICATE","DODUO","PONYTA","HOOTHOOT","MURKROW","STANTLER","MILTANK","DODUO","RATICATE"}) },
  ROUTE_18={ tier=6, grass=habitat(
    {"SPEAROW","RATICATE","DODUO","PONYTA","SPEAROW","RATICATE","DODUO","PONYTA","FEAROW","DODRIO"},
    {"RATICATE","HOOTHOOT","DODUO","PONYTA","RATICATE","HOOTHOOT","DODUO","PONYTA","MURKROW","HOUNDOUR"},
    {"SPEAROW","RATICATE","DODUO","PONYTA","HOOTHOOT","FEAROW","DODRIO","MURKROW","DODUO","HOUNDOUR"}) },
  SAFARI_ZONE_CENTER={ tier=6, grass=habitat({"NIDORAN_M","NIDORAN_F","RHYHORN","EXEGGCUTE","VENONAT","PARAS","TAUROS","CHANSEY","SCYTHER","PINSIR"}) },
  SAFARI_ZONE_NORTH={ tier=6, grass=habitat({"NIDORAN_M","NIDORAN_F","RHYHORN","PARAS","EXEGGCUTE","NIDORINO","NIDORINA","STANTLER","TAUROS","CHANSEY"}) },
  SAFARI_ZONE_EAST={ tier=6, grass=habitat({"DODUO","NIDORAN_F","PARAS","EXEGGCUTE","NIDORINO","PARASECT","GIRAFARIG","HERACROSS","KANGASKHAN","SCYTHER"}) },
  SAFARI_ZONE_WEST={ tier=6, grass=habitat({"DODUO","NIDORAN_M","VENONAT","EXEGGCUTE","NIDORINA","VENOMOTH","AIPOM","SMEARGLE","KANGASKHAN","PINSIR"}) },
  ROUTE_19={ tier=7, water=habitat({"TENTACOOL","TENTACOOL","KRABBY","HORSEA","TENTACOOL","REMORAID","KRABBY","HORSEA","QWILFISH","REMORAID"}) },
  ROUTE_20={ tier=7, water=habitat({"TENTACOOL","TENTACOOL","SHELLDER","CHINCHOU","TENTACOOL","CORSOLA","SHELLDER","CHINCHOU","MANTINE","CORSOLA"}) },
  ROUTE_21={ tier=7,
    grass=habitat(
      {"RATTATA","PIDGEY","RATICATE","TANGELA","RATTATA","PIDGEY","RATICATE","TANGELA","AIPOM","SMEARGLE"},
      {"RATICATE","HOOTHOOT","RATTATA","TANGELA","RATICATE","HOOTHOOT","RATTATA","TANGELA","AIPOM","MURKROW"},
      {"RATTATA","PIDGEY","RATICATE","HOOTHOOT","TANGELA","MURKROW","AIPOM","RATTATA","TANGELA","SMEARGLE"}),
    water=habitat({"TENTACOOL","MARILL","WOOPER","TENTACOOL","MARILL","WOOPER","REMORAID","MANTINE","MARILL",{"TOTODILE",20}}) },
  CRYSTAL_251_NAVEL_ISLE={ tier=8,
    grass=habitat(
      {"KRABBY","EXEGGCUTE","KRABBY","TANGELA","FARFETCHD","MARILL","HOPPIP","SUNFLORA","YANMA","PINSIR"},
      {"KRABBY","EXEGGCUTE","KRABBY","TANGELA","HOOTHOOT","WOOPER","SPINARAK","MURKROW","YANMA","PINSIR"},
      {"KRABBY","EXEGGCUTE","KRABBY","TANGELA","FARFETCHD","MARILL","HOPPIP","MURKROW","YANMA","PINSIR"}),
    water=habitat({"TENTACOOL","TENTACOOL","KRABBY","CHINCHOU","TENTACOOL","CORSOLA","REMORAID","QWILFISH","MANTINE","DRATINI"}) },
  SEAFOAM_ISLANDS_1F={ tier=7, grass=habitat({"SEEL","SLOWPOKE","SHELLDER","SEEL","SLOWPOKE","SHELLDER","SWINUB","SEEL","SLOWPOKE",{"SQUIRTLE",20}}) },
  SEAFOAM_ISLANDS_B1F={ tier=7, grass=habitat({"SEEL","HORSEA","SHELLDER","SEEL","HORSEA","SHELLDER","DEWGONG","SMOOCHUM","DELIBIRD","SNEASEL"}) },
  SEAFOAM_ISLANDS_B2F={ tier=7, grass=habitat({"SEEL","SLOWPOKE","SWINUB","SEEL","SLOWPOKE","SWINUB","SLOWBRO","SMOOCHUM","DELIBIRD","SNEASEL"}) },
  SEAFOAM_ISLANDS_B3F={ tier=7, grass=habitat({"SLOWPOKE","SEEL","SHELLDER","SLOWPOKE","SEEL","SHELLDER","DEWGONG","SMOOCHUM","PILOSWINE","KABUTO"}) },
  SEAFOAM_ISLANDS_B4F={ tier=7, grass=habitat({"HORSEA","SHELLDER","SEEL","HORSEA","SHELLDER","SEEL","SLOWBRO","DEWGONG","SNEASEL","OMANYTE"}) },
  POKEMON_MANSION_1F={ tier=7, grass=habitat(
    {"KOFFING","GROWLITHE","GRIMER","SLUGMA","KOFFING","GROWLITHE","GRIMER","SLUGMA","HOUNDOUR",{"CHARMANDER",25}},
    {"KOFFING","VULPIX","GRIMER","SLUGMA","KOFFING","VULPIX","GRIMER","SLUGMA","HOUNDOUR",{"CHARMANDER",25}},
    {"KOFFING","GROWLITHE","GRIMER","SLUGMA","HOUNDOUR","KOFFING","GRIMER","SLUGMA","GROWLITHE",{"CHARMANDER",25}}) },
  POKEMON_MANSION_2F={ tier=7, grass=habitat(
    {"GROWLITHE","KOFFING","PONYTA","GRIMER","SLUGMA","WEEZING","MUK","MAGBY","HOUNDOUR","MAGMAR"},
    {"VULPIX","KOFFING","PONYTA","GRIMER","SLUGMA","HOUNDOUR","MUK","MAGBY","WEEZING","MAGMAR"},
    {"GROWLITHE","KOFFING","PONYTA","GRIMER","SLUGMA","HOUNDOUR","MUK","MAGBY","WEEZING","MAGMAR"}) },
  POKEMON_MANSION_3F={ tier=7, grass=habitat(
    {"KOFFING","GROWLITHE","GRIMER","SLUGMA","KOFFING","GROWLITHE","GRIMER","WEEZING","HOUNDOUR",{"CYNDAQUIL",25}},
    {"KOFFING","VULPIX","GRIMER","SLUGMA","KOFFING","VULPIX","GRIMER","WEEZING","HOUNDOUR",{"CYNDAQUIL",25}},
    {"KOFFING","GROWLITHE","GRIMER","SLUGMA","HOUNDOUR","KOFFING","GRIMER","WEEZING","GROWLITHE",{"CYNDAQUIL",25}}) },
  POKEMON_MANSION_B1F={ tier=7, grass=habitat({"KOFFING","WEEZING","GRIMER","MUK","SLUGMA","MAGMAR","HOUNDOUR","HOUNDOOM","RAPIDASH","DITTO"}) },
  ROUTE_23={ tier=8, grass=habitat(
    {"FEAROW","ARBOK","DITTO","SPEAROW","PHANPY","DONPHAN","GLIGAR","SKARMORY","TYROGUE","LARVITAR"},
    {"FEAROW","ARBOK","DITTO","MURKROW","PHANPY","DONPHAN","GLIGAR","SKARMORY","SNEASEL","LARVITAR"},
    {"FEAROW","ARBOK","DITTO","MURKROW","PHANPY","DONPHAN","GLIGAR","SKARMORY","TYROGUE","LARVITAR"}) },
  VICTORY_ROAD_1F={ tier=8, grass=habitat({"MACHOP","GEODUDE","ZUBAT","ONIX","GRAVELER","GOLBAT","MACHOKE","GLIGAR","SKARMORY","LARVITAR"}) },
  VICTORY_ROAD_2F={ tier=8, grass=habitat({"MACHOP","GEODUDE","ONIX","MACHOKE","GOLBAT","MAROWAK","GRAVELER","GLIGAR","SNEASEL","LARVITAR"}) },
  VICTORY_ROAD_3F={ tier=8, grass=habitat({"MACHOKE","GRAVELER","GOLBAT","ONIX","MAROWAK","RHYDON","GLIGAR","SKARMORY","PUPITAR","AERODACTYL"}) },
  CERULEAN_CAVE_1F={ tier=9, grass=habitat({"GOLBAT","HYPNO","MAGNETON","DODRIO","GOLBAT","HYPNO","MAGNETON","KADABRA","XATU","WOBBUFFET"}) },
  CERULEAN_CAVE_2F={ tier=9, grass=habitat({"DODRIO","VENOMOTH","KADABRA","RHYDON","DODRIO","VENOMOTH","KADABRA","MAROWAK","DONPHAN","PILOSWINE"}) },
  CERULEAN_CAVE_B1F={ tier=9, grass=habitat({"RHYDON","MAROWAK","ELECTRODE","CHANSEY","RHYDON","MAROWAK","ELECTRODE","STEELIX","HOUNDOOM","URSARING"}) },
}

return E
