-- Canonical Generation II move coverage for Crystal 251.
--
-- Every move introduced by Pokemon Gold/Silver/Crystal (ids 166..251)
-- must appear exactly once.  The probe field names the behavioral contract
-- exercised by move_parity_test.lua.  Shared mechanics deliberately reuse a
-- probe; unique mechanics get a bespoke probe.

return {
  { index=166, id="SKETCH",         probe="sketch", summary="permanently copies the target's last valid move" },
  { index=167, id="TRIPLE_KICK",    probe="triple_kick", summary="up to three separately checked hits with rising power" },
  { index=168, id="THIEF",          probe="thief", summary="damages and steals a non-mail held item when the user is empty-handed" },
  { index=169, id="SPIDER_WEB",     probe="mean_look", summary="prevents the target from switching or escaping" },
  { index=170, id="MIND_READER",    probe="lock_on", summary="makes the user's next attack against this target hit" },
  { index=171, id="NIGHTMARE",      probe="nightmare", summary="afflicts a sleeping target for quarter-HP residual damage" },
  { index=172, id="FLAME_WHEEL",    probe="flame_wheel", summary="damages, may burn, and thaws a frozen user" },
  { index=173, id="SNORE",          probe="snore", summary="works only while asleep and may flinch" },
  { index=174, id="CURSE",          probe="curse", summary="uses the Ghost curse branch or the non-Ghost stat branch" },
  { index=175, id="FLAIL",          probe="hp_scaled_damage", summary="power rises as the user's HP falls" },
  { index=176, id="CONVERSION2",    probe="conversion2", summary="changes to a type resistant or immune to the target's last move" },
  { index=177, id="AEROBLAST",      probe="high_crit_damage", summary="ordinary damage with an elevated critical-hit rate" },
  { index=178, id="COTTON_SPORE",   probe="stage", who="target", stat="speed", delta=-2, summary="lowers target Speed by two stages" },
  { index=179, id="REVERSAL",       probe="hp_scaled_damage", summary="power rises as the user's HP falls" },
  { index=180, id="SPITE",          probe="spite", summary="removes 2-5 PP from the target's last move" },
  { index=181, id="POWDER_SNOW",    probe="secondary_status", status="FRZ", summary="damages and may freeze" },
  { index=182, id="PROTECT",        probe="protect", summary="blocks attacks and shares the consecutive-use failure chain" },
  { index=183, id="MACH_PUNCH",     probe="priority_damage", priority=1, summary="deals damage with positive priority" },
  { index=184, id="SCARY_FACE",     probe="stage", who="target", stat="speed", delta=-2, summary="lowers target Speed by two stages" },
  { index=185, id="FAINT_ATTACK",   probe="always_hit", summary="damages without an accuracy check" },
  { index=186, id="SWEET_KISS",     probe="confusion", summary="confuses the target" },
  { index=187, id="BELLY_DRUM",     probe="belly_drum", summary="spends half max HP and maximizes Attack" },
  { index=188, id="SLUDGE_BOMB",    probe="secondary_status", status="PSN", summary="damages and may poison" },
  { index=189, id="MUD_SLAP",       probe="secondary_stage", who="target", stat="accuracy", delta=-1, summary="damages and lowers Accuracy" },
  { index=190, id="OCTAZOOKA",      probe="secondary_stage", who="target", stat="accuracy", delta=-1, summary="damages and may lower Accuracy" },
  { index=191, id="SPIKES",         probe="spikes", summary="places the single Generation II Spikes layer" },
  { index=192, id="ZAP_CANNON",     probe="secondary_status", status="PAR", summary="damages and always paralyzes on a hit" },
  { index=193, id="FORESIGHT",      probe="foresight", summary="identifies the target and removes its evasion advantage" },
  { index=194, id="DESTINY_BOND",   probe="destiny_bond", summary="takes the attacker down when the user is KO'd by its move" },
  { index=195, id="PERISH_SONG",    probe="perish_song", summary="starts a three-turn perish count that switching clears" },
  { index=196, id="ICY_WIND",       probe="secondary_stage", who="target", stat="speed", delta=-1, summary="damages and lowers Speed" },
  { index=197, id="DETECT",         probe="protect", summary="blocks attacks and shares the consecutive-use failure chain" },
  { index=198, id="BONE_RUSH",      probe="multi_hit", summary="hits two to five times" },
  { index=199, id="LOCK_ON",        probe="lock_on", summary="makes the user's next attack against this target hit" },
  { index=200, id="OUTRAGE",        probe="rampage", summary="locks the user for 2-3 turns and then confuses it" },
  { index=201, id="SANDSTORM",      probe="sandstorm", summary="starts five turns of damaging sandstorm weather" },
  { index=202, id="GIGA_DRAIN",     probe="drain", summary="heals the user for half the damage dealt" },
  { index=203, id="ENDURE",         probe="endure", summary="leaves the user at 1 HP and shares the Protect failure chain" },
  { index=204, id="CHARM",          probe="stage", who="target", stat="attack", delta=-2, summary="lowers target Attack by two stages" },
  { index=205, id="ROLLOUT",        probe="rollout", summary="locks five turns, doubles power, and interacts with Defense Curl" },
  { index=206, id="FALSE_SWIPE",    probe="false_swipe", summary="damages but cannot reduce the target below 1 HP" },
  { index=207, id="SWAGGER",        probe="swagger", summary="raises target Attack two stages and confuses it" },
  { index=208, id="MILK_DRINK",     probe="heal_half", summary="restores half the user's maximum HP" },
  { index=209, id="SPARK",          probe="secondary_status", status="PAR", summary="damages and may paralyze" },
  { index=210, id="FURY_CUTTER",    probe="fury_cutter", summary="doubles power on consecutive successful uses and resets otherwise" },
  { index=211, id="STEEL_WING",     probe="secondary_stage", who="user", stat="defense", delta=1, summary="damages and may raise Defense" },
  { index=212, id="MEAN_LOOK",      probe="mean_look", summary="prevents the target from switching or escaping" },
  { index=213, id="ATTRACT",        probe="attract", summary="infatuates only a compatible opposite-gender target" },
  { index=214, id="SLEEP_TALK",     probe="sleep_talk", summary="calls an eligible move while asleep without spending that move's PP" },
  { index=215, id="HEAL_BELL",      probe="heal_bell", summary="cures status across the user's party" },
  { index=216, id="RETURN",         probe="happiness_damage", direction="up", summary="power rises with happiness" },
  { index=217, id="PRESENT",        probe="present", summary="randomly deals 40/80/120-power damage or heals one quarter" },
  { index=218, id="FRUSTRATION",    probe="happiness_damage", direction="down", summary="power falls as happiness rises" },
  { index=219, id="SAFEGUARD",      probe="safeguard", summary="prevents status and confusion for five turns" },
  { index=220, id="PAIN_SPLIT",     probe="pain_split", summary="sets both current HP values to their average, capped by max HP" },
  { index=221, id="SACRED_FIRE",    probe="sacred_fire", summary="damages, may burn, and thaws a frozen user" },
  { index=222, id="MAGNITUDE",      probe="magnitude", summary="chooses Magnitude 4-10 with the Crystal power distribution" },
  { index=223, id="DYNAMICPUNCH",   probe="secondary_confusion", summary="damages and always confuses on a hit" },
  { index=224, id="MEGAHORN",       probe="damage", summary="ordinary damaging move" },
  { index=225, id="DRAGONBREATH",   probe="secondary_status", status="PAR", summary="damages and may paralyze" },
  { index=226, id="BATON_PASS",     probe="baton_pass", summary="switches while passing stat stages and passable volatile state" },
  { index=227, id="ENCORE",         probe="encore", summary="forces the target to repeat its last move for 3-6 turns" },
  { index=228, id="PURSUIT",        probe="pursuit", summary="intercepts a switch and doubles damage before the target leaves" },
  { index=229, id="RAPID_SPIN",     probe="rapid_spin", summary="damages and clears trapping, Leech Seed, and the user's Spikes" },
  { index=230, id="SWEET_SCENT",    probe="stage", who="target", stat="evasion", delta=-1, summary="lowers target Evasion one stage" },
  { index=231, id="IRON_TAIL",      probe="secondary_stage", who="target", stat="defense", delta=-1, summary="damages and may lower Defense" },
  { index=232, id="METAL_CLAW",     probe="secondary_stage", who="user", stat="attack", delta=1, summary="damages and may raise Attack" },
  { index=233, id="VITAL_THROW",    probe="always_hit_priority", priority=-1, summary="always hits with negative priority" },
  { index=234, id="MORNING_SUN",    probe="weather_heal", summary="heals according to the current weather" },
  { index=235, id="SYNTHESIS",      probe="weather_heal", summary="heals according to the current weather" },
  { index=236, id="MOONLIGHT",      probe="weather_heal", summary="heals according to the current weather" },
  { index=237, id="HIDDEN_POWER",   probe="hidden_power", summary="derives type and power from DVs" },
  { index=238, id="CROSS_CHOP",     probe="high_crit_damage", summary="ordinary damage with an elevated critical-hit rate" },
  { index=239, id="TWISTER",        probe="twister", summary="may flinch and doubles damage against a target using Fly" },
  { index=240, id="RAIN_DANCE",     probe="weather", weather="rain", summary="starts five turns of rain" },
  { index=241, id="SUNNY_DAY",      probe="weather", weather="sun", summary="starts five turns of harsh sunlight" },
  { index=242, id="CRUNCH",         probe="secondary_stage", who="target", stat="specialDefense", delta=-1, summary="damages and may lower Special Defense" },
  { index=243, id="MIRROR_COAT",    probe="mirror_coat", summary="returns double the last special damage from the target" },
  { index=244, id="PSYCH_UP",       probe="psych_up", summary="copies the target's stat stages" },
  { index=245, id="EXTREMESPEED",   probe="priority_damage", priority=1, summary="deals damage with positive priority" },
  { index=246, id="ANCIENTPOWER",   probe="ancientpower", summary="may raise every battle stat represented by the engine one stage" },
  { index=247, id="SHADOW_BALL",    probe="secondary_stage", who="target", stat="specialDefense", delta=-1, enemySpecies="MEW", summary="damages and may lower Special Defense" },
  { index=248, id="FUTURE_SIGHT",   probe="future_sight", summary="schedules delayed damage against the opposing slot" },
  { index=249, id="ROCK_SMASH",     probe="secondary_stage", who="target", stat="defense", delta=-1, summary="damages and may lower Defense" },
  { index=250, id="WHIRLPOOL",      probe="trap", summary="traps for two to five turns using Generation II trapping rules" },
  { index=251, id="BEAT_UP",        probe="beat_up", summary="one Dark-type hit for each healthy, status-free party member" },
}
